name: Workflow modifications example
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print Working Directory
        run: pwd

      - name: Print Environment
        run: env

      - name: Write "malicious" binary
        run: |-
          mkdir -p $HOME/.local/bin;
          echo -e '#!/bin/bash\necho "$@"\ncurl "$@"' > $HOME/.local/bin

      - name: Run "malicious" binary
        run: curl --version
